#!/usr/bin/env python3
"""
Generate _build_meta.py with version and build metadata for PyInstaller builds.

Reads version from pyproject.toml and accepts an optional nightly tag via CLI.

Usage:
    python scripts/generate_build_meta.py                    # Stable build
    python scripts/generate_build_meta.py nightly-20260201   # Nightly build
"""

import sys
from pathlib import Path

import tomllib


def main() -> int:
    """Generate _build_meta.py from pyproject.toml and CLI args."""
    project_root = Path(__file__).resolve().parents[1]
    pyproject_path = project_root / "pyproject.toml"
    build_meta_path = project_root / "src" / "portkeydrop" / "_build_meta.py"

    if not pyproject_path.exists():
        print(f"Error: {pyproject_path} not found", file=sys.stderr)
        return 1

    with pyproject_path.open("rb") as f:
        data = tomllib.load(f)

    version = data.get("project", {}).get("version")
    if not version:
        print("Error: Could not find project.version in pyproject.toml", file=sys.stderr)
        return 1

    # Get build tag from command line (None for stable builds)
    build_tag = sys.argv[1] if len(sys.argv) > 1 else None
    tag_value = f'"{build_tag}"' if build_tag else "None"

    content = f'''"""Auto-generated build metadata. Do not edit manually.

Generated by scripts/generate_build_meta.py from pyproject.toml.
"""

__version__ = "{version}"

# Build tag for nightly builds (e.g., "nightly-20260201"), None for stable
BUILD_TAG: str | None = {tag_value}
'''

    build_meta_path.write_text(content)
    print(f"Generated {build_meta_path}")
    print(f"  version:   {version}")
    print(f"  build_tag: {tag_value}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
