name: Update WordPress on release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-wordpress-page:
    uses: ./.github/workflows/push-releases.yml
    with:
      wp_page_id: ${{ vars.WP_PAGE_ID }}
    secrets:
      WP_APPLICATION_PASSWORD: ${{ secrets.WP_APPLICATION_PASSWORD }}
      WP_SITE_URL: ${{ secrets.WP_SITE_URL }}
      WP_USERNAME: ${{ secrets.WP_USERNAME }}
